### ISSUE TITLE
Regex incorrect?

### ISSUE THREAD

**Issue by joefiorini** [thatportugueseguy/ocaml-dotenv#1]
I noticed an issue when setting an environment variable like:

```
DEBUG=true
```

The value that dotenv is reading for this variable `"ue"`. At first I thought maybe it was because `tr` is a shell command. So I tried `lsue` and the value it read out was `"lsue"`.Looking at the code I noticed the `\\t` and `\\r` in the regex. So I tried making it `"pfue"` and again I got `"ue"`.

My working theory is that the escapes are incorrect and Ocaml is reading the regex as `"[rtfv]"` instead of what I think you intended `"[\r\t\f\v]"`.

**Comment by thatportugueseguy** [comment]
Hey, you are right, there's an issue with that regex.

I have been meaning to change this for a while, but didn't have much time to. It turns out that `Str` is not a great library to use because it's not thread safe. 

In the beginning, i considered using PCRE but didn't want to add other dependencies, this was a bad choice :)

And i will also add tests, to make this slighly less error prone.

I will try to do it this week.

Thanks for raising this issue

**Comment by thatportugueseguy** [comment]
@joefiorini This has been fixed and updated. Please try with the new version and let me know, thank you :)

**Comment by thatportugueseguy** [comment]
There was an issue with releasing opam packages: https://github.com/ocaml/opam-repository/issues/16364

The new version is now available.
